import {
  ArrowRight,
  Award,
  BadgeCheck,
  Building2,
  CalendarCheck,
  CalendarClock,
  Check,
  ChevronLeft,
  ChevronRight,
  ChevronsLeftRight,
  Clock,
  CreditCard,
  FileText,
  Flame,
  Gauge,
  GitCompareArrows,
  Home,
  Leaf,
  Mail,
  MapPin,
  Menu,
  MessagesSquare,
  Package,
  Percent,
  Phone,
  PhoneCall,
  Plus,
  Quote,
  RefreshCw,
  Ruler,
  Search,
  Send,
  ShieldCheck,
  Siren,
  Smile,
  Star,
  ThermometerSun,
  TrendingDown,
  Users,
  Wind,
  Wrench,
  X,
  Zap,
} from 'lucide-react';
import type { IconName, IconRegistry } from '@/types';

/**
 * Maps the `data-lucide` names used throughout the design components onto
 * their React counterparts, so data files stay serialisable strings.
 */
export const icons: IconRegistry = {
  'arrow-right': ArrowRight,
  award: Award,
  'badge-check': BadgeCheck,
  'building-2': Building2,
  'calendar-check': CalendarCheck,
  'calendar-clock': CalendarClock,
  check: Check,
  'chevron-left': ChevronLeft,
  'chevron-right': ChevronRight,
  'chevrons-left-right': ChevronsLeftRight,
  clock: Clock,
  'credit-card': CreditCard,
  'file-text': FileText,
  flame: Flame,
  gauge: Gauge,
  'git-compare-arrows': GitCompareArrows,
  home: Home,
  leaf: Leaf,
  mail: Mail,
  'map-pin': MapPin,
  menu: Menu,
  'messages-square': MessagesSquare,
  package: Package,
  percent: Percent,
  phone: Phone,
  'phone-call': PhoneCall,
  plus: Plus,
  quote: Quote,
  'refresh-cw': RefreshCw,
  ruler: Ruler,
  search: Search,
  send: Send,
  'shield-check': ShieldCheck,
  siren: Siren,
  smile: Smile,
  star: Star,
  'thermometer-sun': ThermometerSun,
  'trending-down': TrendingDown,
  users: Users,
  wind: Wind,
  wrench: Wrench,
  x: X,
  zap: Zap,
};

export function getIcon(name: IconName) {
  return icons[name];
}
